// b140.17.4 — Release-readiness Stage 5: aggregator + report.
//
// Reads the 4 per-stage JSON reports written into
// `target/release_report_stage{1..4}.json` by the other tests in this
// suite, validates each, and produces:
//   - target/release_report.json  (combined machine-readable)
//   - target/release_report.md    (human summary)
//
// The cargo alias `cargo release-readiness` (see .cargo/config.toml)
// runs all 5 stages. Because integration-test binaries run in parallel
// the FIRST invocation may emit a warning for missing per-stage JSONs;
// re-running stage5 alone (or invoking the alias a second time) picks
// them up and produces the final aggregated report.
//
// Fail tolerances (per CLAUDE.md "loose internal guardrail" doctrine):
//   - stage1: zero NaN/Inf, zero 1-bin phase spikes >60° (target/PEQ/SUM)
//             and >90° (FIR realised), per-band FIR peak in (0, 100)
//   - stage2: 0 failures across the matrix (490 runs)
//   - stage3: 0 failures across the export sweep (120 runs)
//   - stage4: per-band IR finite, SUM IR finite, alignment delta > 0.001 dB
//
// A stage with `failures > 0` causes stage5 itself to fail — that is
// the release gate.

use serde_json::Value;
use std::path::{Path, PathBuf};

fn target_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("target")
}

fn read_json(path: &Path) -> Option<Value> {
    let bytes = std::fs::read(path).ok()?;
    serde_json::from_slice(&bytes).ok()
}

#[test]
fn release_readiness_stage5_aggregate() {
    let dir = target_dir();
    let stages = [
        ("stage1", "release_report_stage1.json"),
        ("stage2", "release_report_stage2.json"),
        ("stage3", "release_report_stage3.json"),
        ("stage4", "release_report_stage4.json"),
    ];

    let mut entries = serde_json::Map::new();
    let mut missing = Vec::<String>::new();
    let mut hard_failures = Vec::<String>::new();
    let mut md = String::new();

    md.push_str("# PhaseForge — Release-Readiness Report\n\n");
    md.push_str("Generated by `cargo release-readiness` (stage 5 aggregator).\n\n");
    md.push_str("| Stage | Status | Runs | Failures | Notes |\n");
    md.push_str("|-------|--------|------|----------|-------|\n");

    for (name, fname) in stages.iter() {
        let path = dir.join(fname);
        match read_json(&path) {
            None => {
                missing.push((*name).into());
                md.push_str(&format!(
                    "| {name} | MISSING | – | – | {} not found — run that stage |\n",
                    path.display()
                ));
                entries.insert((*name).to_string(), Value::Null);
            }
            Some(v) => {
                let failures = v
                    .get("failures")
                    .and_then(Value::as_u64)
                    .unwrap_or(0);
                let total = v
                    .get("total_runs")
                    .and_then(Value::as_u64)
                    .unwrap_or(0);
                let status = if failures == 0 { "OK" } else { "FAIL" };
                let notes = match *name {
                    "stage1" => v
                        .get("sum")
                        .and_then(|s| s.get("phase_spikes"))
                        .map(|n| format!("SUM spikes={}", n))
                        .unwrap_or_default(),
                    "stage2" => format!("pipeline matrix"),
                    "stage3" => format!("export sweep"),
                    "stage4" => v
                        .get("sum")
                        .and_then(|s| s.get("alignment_delta_db"))
                        .and_then(Value::as_f64)
                        .map(|d| format!("align Δ={:.4} dB @ 1 kHz", d))
                        .unwrap_or_default(),
                    _ => String::new(),
                };
                md.push_str(&format!(
                    "| {name} | {status} | {total} | {failures} | {notes} |\n"
                ));
                if failures != 0 {
                    hard_failures.push(format!(
                        "{name}: {failures} failures (see {})",
                        path.display()
                    ));
                }
                entries.insert((*name).to_string(), v);
            }
        }
    }

    md.push('\n');
    if !missing.is_empty() {
        md.push_str(&format!(
            "**Missing stages**: {}. Run `cargo release-readiness` again.\n\n",
            missing.join(", ")
        ));
    }
    if !hard_failures.is_empty() {
        md.push_str("**Hard failures**:\n");
        for f in &hard_failures {
            md.push_str(&format!("- {f}\n"));
        }
        md.push('\n');
    }
    if missing.is_empty() && hard_failures.is_empty() {
        md.push_str("**All stages PASS — release gate is open.**\n");
    }

    let combined = serde_json::json!({
        "version": "b140.17.4 stage5",
        "stages_present": entries.len() - missing.len(),
        "stages_missing": &missing,
        "hard_failures": &hard_failures,
        "entries": Value::Object(entries),
    });

    let _ = std::fs::create_dir_all(&dir);
    std::fs::write(
        dir.join("release_report.json"),
        serde_json::to_string_pretty(&combined).unwrap(),
    )
    .expect("write release_report.json");
    std::fs::write(dir.join("release_report.md"), md.clone())
        .expect("write release_report.md");

    eprintln!(
        "[stage5] missing={} hard_failures={} — wrote {}",
        missing.len(),
        hard_failures.len(),
        dir.join("release_report.md").display()
    );
    eprintln!("{}", md);

    assert!(
        hard_failures.is_empty(),
        "release gate FAIL: {:?}",
        hard_failures
    );
}
